#!/bin/bash

statsfile="${1}"
port="${2}"

while read phrase
do
  /bin/time -f '%e' -a -o "${statsfile}" curl -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d "{\"text\" : \"${phrase}\"}" http://localhost:${port}/analyze
done
